name: Lint (Python)

on:
  pull_request:
    paths: ['src/**','tests/**','pyproject.toml','.ruff.toml','.github/workflows/lint.yml']
  push:
    branches: [ main ]
    paths: ['src/**','tests/**','pyproject.toml','.ruff.toml','.github/workflows/lint.yml']

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ruff (lint)
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.12.0
          args: check . --config pyproject.toml --output-format=github --no-cache

      - name: Ruff (format check)
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.12.0
          args: format --check . --config pyproject.toml --no-cache
